import * as z from 'zod';

// language map with display names for syntax highlighting
export const LANGUAGE_MAP = {
	plaintext: 'Plain Text',
	javascript: 'JavaScript',
	typescript: 'TypeScript',
	python: 'Python',
	java: 'Java',
	c: 'C',
	cpp: 'C++',
	csharp: 'C#',
	php: 'PHP',
	ruby: 'Ruby',
	go: 'Go',
	rust: 'Rust',
	swift: 'Swift',
	kotlin: 'Kotlin',
	scala: 'Scala',
	clojure: 'Clojure',
	haskell: 'Haskell',
	elixir: 'Elixir',
	erlang: 'Erlang',
	dart: 'Dart',
	julia: 'Julia',
	lua: 'Lua',
	perl: 'Perl',
	r: 'R',
	matlab: 'MATLAB',
	ocaml: 'OCaml',
	crystal: 'Crystal',
	html: 'HTML',
	css: 'CSS',
	scss: 'SCSS',
	less: 'Less',
	sass: 'Sass',
	stylus: 'Stylus',
	postcss: 'PostCSS',
	json: 'JSON',
	xml: 'XML',
	yaml: 'YAML',
	toml: 'TOML',
	ini: 'INI',
	csv: 'CSV',
	markdown: 'Markdown',
	mdx: 'MDX',
	latex: 'LaTeX',
	bash: 'Bash',
	shell: 'Shell',
	powershell: 'PowerShell',
	sql: 'SQL',
	dockerfile: 'Dockerfile',
	makefile: 'Makefile',
	cmake: 'CMake',
	nginx: 'Nginx',
	apache: 'Apache',
	graphql: 'GraphQL',
	proto: 'Protocol Buffers',
	prisma: 'Prisma',
	svelte: 'Svelte',
	vue: 'Vue',
	jsx: 'JSX',
	tsx: 'TSX',
	astro: 'Astro',
	'angular-html': 'Angular HTML',
	'angular-ts': 'Angular TypeScript',
	handlebars: 'Handlebars',
	twig: 'Twig',
	'php-html': 'PHP HTML',
	blade: 'Blade',
	assembly: 'Assembly',
	wasm: 'WebAssembly',
} as const;

// derive the supported languages array from the map keys
export const SUPPORTED_LANGUAGES = Object.keys(
	LANGUAGE_MAP
) as readonly (keyof typeof LANGUAGE_MAP)[];

export type SupportedLanguage = keyof typeof LANGUAGE_MAP;

export const getLanguageDisplayName = (languageId: string): string => {
	return LANGUAGE_MAP[languageId as SupportedLanguage] || languageId;
};

export const SupportedLanguageSchema = z.enum(
	Object.keys(LANGUAGE_MAP) as [SupportedLanguage, ...SupportedLanguage[]]
);

// language to file extension mapping for downloads
export const LANGUAGE_EXTENSION_MAP: Record<SupportedLanguage, string> = {
	plaintext: '.txt',
	javascript: '.js',
	typescript: '.ts',
	python: '.py',
	java: '.java',
	c: '.c',
	cpp: '.cpp',
	csharp: '.cs',
	php: '.php',
	ruby: '.rb',
	go: '.go',
	rust: '.rs',
	swift: '.swift',
	kotlin: '.kt',
	scala: '.scala',
	clojure: '.clj',
	haskell: '.hs',
	elixir: '.ex',
	erlang: '.erl',
	dart: '.dart',
	julia: '.jl',
	lua: '.lua',
	perl: '.pl',
	r: '.r',
	matlab: '.m',
	ocaml: '.ml',
	crystal: '.cr',
	html: '.html',
	css: '.css',
	scss: '.scss',
	less: '.less',
	sass: '.sass',
	stylus: '.styl',
	postcss: '.pcss',
	json: '.json',
	xml: '.xml',
	yaml: '.yaml',
	toml: '.toml',
	ini: '.ini',
	csv: '.csv',
	markdown: '.md',
	mdx: '.mdx',
	latex: '.tex',
	bash: '.sh',
	shell: '.sh',
	powershell: '.ps1',
	sql: '.sql',
	dockerfile: '.dockerfile',
	makefile: '.makefile',
	cmake: '.cmake',
	nginx: '.conf',
	apache: '.conf',
	graphql: '.graphql',
	proto: '.proto',
	prisma: '.prisma',
	svelte: '.svelte',
	vue: '.vue',
	jsx: '.jsx',
	tsx: '.tsx',
	astro: '.astro',
	'angular-html': '.html',
	'angular-ts': '.ts',
	handlebars: '.hbs',
	twig: '.twig',
	'php-html': '.php',
	blade: '.blade.php',
	assembly: '.asm',
	wasm: '.wasm',
};

export const getFileExtension = (languageId: string): string => {
	return LANGUAGE_EXTENSION_MAP[languageId as SupportedLanguage] || '.txt';
};
